// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLWZ_9fe0yln35cIy942Yi0agSbK7s3Yg',
    appId: '1:202812506244:web:3bd52730a112b025fb42d1',
    messagingSenderId: '202812506244',
    projectId: 'banking-app-d3be3',
    authDomain: 'banking-app-d3be3.firebaseapp.com',
    storageBucket: 'banking-app-d3be3.firebasestorage.app',
    measurementId: 'G-HH8XVX97LT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8RjSOpcU1umA8ddsh0vCp21MPR44uFgQ',
    appId: '1:202812506244:android:ab3ab0d35178b59afb42d1',
    messagingSenderId: '202812506244',
    projectId: 'banking-app-d3be3',
    storageBucket: 'banking-app-d3be3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALb96shxNdSEUCdboPZaF6ui39w-Tzu1o',
    appId: '1:202812506244:ios:875df0e177749a73fb42d1',
    messagingSenderId: '202812506244',
    projectId: 'banking-app-d3be3',
    storageBucket: 'banking-app-d3be3.firebasestorage.app',
    iosBundleId: 'com.example.mobileBankingApp',
  );
}